"""AeroPub — fleet-aware analysis of aeronautical publications.

The two questions the platform answers, and where each is assembled:

- *"Tell me everything about this."* — :func:`aeropub.dossier.build`
- *"Something was published; what does it mean?"* — :func:`aeropub.bulletin.between_cycles`
- *"What changes next, including what nobody will announce?"* — :func:`aeropub.horizon.horizon`
- *"How does this State actually publish?"* — :func:`aeropub.quality.assess_quality`

Each of those is one body of evidence. :func:`aeropub.lenses.view` arranges it
for one of six readers without ever filtering away a coverage gap, and
:func:`aeropub.api.document` emits any of them as JSON with the citation
still attached to every value.

Everything below those is the machinery they stand on: the AIRAC calendar as
the time spine, :class:`Fact` and :class:`SourceRef` as the attributed core,
:class:`FactStore` resolving the Consolidated Effective State, the AIP index
saying what a publication should contain, and the source registry saying what
we are actually watching.

The connectors live in subpackages — :mod:`aeropub.faa` today — and are not
imported here, so ``import aeropub`` costs nothing a caller has not asked for.
"""

from aeropub.acap import load_aircraft, merge
from aeropub.aip import (
    AipCoverage,
    HoldingState,
    Section,
    SectionHolding,
    aerodrome_sections,
    section,
)
from aeropub.aircraft import (
    AircraftType,
    PavementCheck,
    PavementRating,
    Characteristic,
    Origin,
    PavementVerdict,
    RatingSystem,
    accommodates,
    code_letter,
    code_number,
    compare_pavement,
    reference_code,
    rffs_category,
)
from aeropub.airac import (
    AiracCycle,
    current_cycle,
    cycle_for,
    cycles_apart,
    cycles_in_year,
)
from aeropub.changes import Change, ChangeKind, diff_cycles, diff_effective
from aeropub.credentials import CredentialStore, MissingCredential
from aeropub.currency import Currency, DataCurrency, assess_currency
from aeropub.facts import Fact, FactStore, Precedence
from aeropub.impact import Direction, Impact, assess
from aeropub.ingest import load_facts
from aeropub.manifest import ManifestError, sha256_of
from aeropub.obstacles import (
    DepartureArea,
    OLS_INSTRUMENT_DEPARTURE,
    PANS_OPS_STRAIGHT,
    Obstacle,
    ObstacleChange,
    ObstacleReview,
    Penetration,
    TrackOffset,
    compare_cycles,
    decompose,
    penetrates_ois,
    required_gradient,
    review_runway,
)
from aeropub.provenance import Confidence, SourceRef
from aeropub.quality import FindingKind, QualityFinding, QualityReport, assess_quality
from aeropub.store import SqliteFactStore, open_store
from aeropub.sweep import (
    AerodromeExposure,
    GroupRedundancy,
    NetworkSweep,
    sweep,
)
from aeropub.suitability import (
    Assessment,
    Check,
    Note,
    Suitability,
    assess_suitability,
    minimum_runway_width_m,
)
from aeropub.api import Licensing, document, dumps, ndjson, to_json
from aeropub.bulletin import Attention, ChangeBulletin, between_cycles, compile_bulletin
from aeropub.dossier import AerodromeDossier, SectionEntry, build_dossier
from aeropub.entities import aerodrome_of, covers, scope_of
from aeropub.fleet import (
    Basis,
    FleetLibrary,
    FleetScreen,
    Holding,
    OperatorFleet,
    OperatorRecord,
    Registration,
    OperatorSegment,
    TypeCoverage,
    TypeGap,
    TypeReference,
    TypeScreen,
    fleet_of,
    library_template,
    load_library,
    merge_libraries,
    route_profile,
    screen,
)
from aeropub.runtime import (
    Breaker,
    BreakerState,
    Heartbeat,
    HostBudget,
    Outage,
    Restraint,
    RuntimeReport,
    Supervisor,
)
from aeropub.charts import (
    Chart,
    ChartKind,
    ChartRegister,
    ChartReview,
    Discrepancy,
    Expectation,
    MinimaChange,
    Minimum,
    Requirement,
    Unexplained,
    Usability,
    compare_minima,
    load_register,
    register_template,
    review_charts,
    usable,
)
from aeropub.route import (
    Altimetry,
    AltimetryChange,
    Jurisdiction,
    JurisdictionCover,
    OpenItem,
    Route,
    RouteDossier,
    build_route_dossier,
)
from aeropub.ats import (
    AtsStructure,
    CruisingLevels,
    FiledRoute,
    LevelFinding,
    Resolution,
    RouteExpansion,
    RouteSegment,
    SignificantPoint,
    expand,
    load_ats_structure,
    notams_on_route,
    parse_route_string,
    route_entities,
    screen_levels,
    structure_template,
)
from aeropub.charts import (
    Constraint,
    ConstraintKind,
    GradientFinding,
    Procedure,
    ProcedureKind,
    ProcedureLeg,
    ProcedureLink,
    connecting_procedures,
    load_procedures,
    procedure_template,
    screen_climb,
    screen_descent,
)
from aeropub.airspace import (
    Airspace,
    AirspaceClass,
    AirspaceStructure,
    AirspaceType,
    AirspaceView,
    CarriageRequirement,
    ClassTransition,
    airspace_template,
    load_airspace,
    view_airspace,
)
from aeropub.hazards import (
    Activation,
    Clearance,
    ClearanceFinding,
    ClearanceKind,
    Hazard,
    HazardKind,
    HazardRegister,
    HazardScreen,
    hazard_template,
    load_hazards,
    notams_on_hazards,
    screen_clearances,
    screen_hazards,
)
from aeropub.navaids import (
    Navaid,
    NavaidKind,
    NavaidRegister,
    NavaidStatus,
    NavaidUse,
    alternatives_to,
    load_navaids,
    navaid_template,
    screen_navaids,
)
from aeropub.holding import (
    Entry,
    EntrySector,
    HoldingFinding,
    HoldingPattern,
    HoldingRegister,
    SpeedBasis,
    TurnDirection,
    entry_for,
    holding_template,
    load_holding,
    max_holding_speed_kt,
    screen_holding,
    standard_outbound_time_min,
)
from aeropub.diagram import (
    Band,
    Lane,
    NetworkDiagram,
    RouteDiagram,
    diagram_for,
    network_for,
    network_html,
    network_svg,
    route_html,
    route_svg,
)
from aeropub.geo import (
    Bounds,
    CoordinateError,
    Position,
    bounds_of,
    distance_disagreement,
    format_coordinate,
    great_circle_nm,
    great_circle_path,
    initial_bearing,
    intermediate,
    mercator,
    parse_coordinate,
    parse_position,
)
from aeropub.planview import (
    Airway,
    PlanView,
    PlottedPoint,
    RouteLeg,
    plan_html,
    plan_svg,
    plan_view,
)
from aeropub.gate import (
    Attestation,
    Disposition,
    GateLog,
    Release,
    ReviewGate,
    StaleAttestation,
    fingerprint,
    review,
)
from aeropub.horizon import Horizon, Transition, Trigger, horizon
from aeropub.lenses import LENSES, Audience, Lens, LensView, lens_for, view
from aeropub.notam import Notam, NotamKind, QLine
from aeropub.operator import (
    Exposure,
    ExposureFinding,
    Fleet,
    Network,
    NetworkEntry,
    OperatorAssessment,
    OperatorProfile,
    Role,
    assess_operator,
    load_profile,
    worst_exposure,
)
from aeropub.notam_register import (
    ForceState,
    NotamRegister,
    RegisteredNotam,
    Subject,
    SubjectKind,
)
from aeropub.trip import (
    BIZAV_SECTIONS,
    LegAssessment,
    Trip,
    TripAssessment,
    assess_trip,
)
from aeropub.validation import Finding, Severity, validate
from aeropub.render import render_dossier
from aeropub.retrospect import (
    Blindness,
    LateArrival,
    Retrospect,
    Revision,
    blind_spots,
    retrospect,
)
from aeropub.registry import (
    CheckOutcome,
    CredentialRef,
    CredentialStatus,
    DetectionTier,
    Freshness,
    Redistribution,
    Source,
    SourceFormat,
    SourceKind,
    SourceRegistry,
    SourceState,
    StatusRow,
    render_board,
)

__all__ = [
    "accommodates",
    "Activation",
    "aerodrome_of",
    "aerodrome_sections",
    "AerodromeDossier",
    "AerodromeExposure",
    "AipCoverage",
    "AiracCycle",
    "AircraftType",
    "Airspace",
    "airspace_template",
    "AirspaceClass",
    "AirspaceStructure",
    "AirspaceType",
    "AirspaceView",
    "Airway",
    "alternatives_to",
    "Altimetry",
    "AltimetryChange",
    "assess",
    "assess_currency",
    "assess_operator",
    "assess_quality",
    "assess_suitability",
    "assess_trip",
    "Assessment",
    "AtsStructure",
    "Attention",
    "Attestation",
    "Audience",
    "Band",
    "Basis",
    "between_cycles",
    "BIZAV_SECTIONS",
    "blind_spots",
    "Blindness",
    "Bounds",
    "bounds_of",
    "Breaker",
    "BreakerState",
    "build_dossier",
    "build_route_dossier",
    "CarriageRequirement",
    "Change",
    "ChangeBulletin",
    "ChangeKind",
    "Characteristic",
    "Chart",
    "ChartKind",
    "ChartRegister",
    "ChartReview",
    "Check",
    "CheckOutcome",
    "ClassTransition",
    "Clearance",
    "ClearanceFinding",
    "ClearanceKind",
    "code_letter",
    "code_number",
    "compare_cycles",
    "compare_minima",
    "compare_pavement",
    "compile_bulletin",
    "Confidence",
    "connecting_procedures",
    "Constraint",
    "ConstraintKind",
    "CoordinateError",
    "covers",
    "CredentialRef",
    "CredentialStatus",
    "CredentialStore",
    "CruisingLevels",
    "Currency",
    "current_cycle",
    "cycle_for",
    "cycles_apart",
    "cycles_in_year",
    "DataCurrency",
    "decompose",
    "DepartureArea",
    "DetectionTier",
    "diagram_for",
    "diff_cycles",
    "diff_effective",
    "Direction",
    "Discrepancy",
    "Disposition",
    "distance_disagreement",
    "document",
    "dumps",
    "Entry",
    "entry_for",
    "EntrySector",
    "expand",
    "Expectation",
    "Exposure",
    "ExposureFinding",
    "Fact",
    "FactStore",
    "FiledRoute",
    "Finding",
    "FindingKind",
    "fingerprint",
    "Fleet",
    "fleet_of",
    "FleetLibrary",
    "FleetScreen",
    "ForceState",
    "format_coordinate",
    "Freshness",
    "GateLog",
    "GradientFinding",
    "great_circle_nm",
    "great_circle_path",
    "GroupRedundancy",
    "Hazard",
    "hazard_template",
    "HazardKind",
    "HazardRegister",
    "HazardScreen",
    "Heartbeat",
    "Holding",
    "holding_template",
    "HoldingFinding",
    "HoldingPattern",
    "HoldingRegister",
    "HoldingState",
    "horizon",
    "Horizon",
    "HostBudget",
    "Impact",
    "initial_bearing",
    "intermediate",
    "Jurisdiction",
    "JurisdictionCover",
    "Lane",
    "LateArrival",
    "LegAssessment",
    "Lens",
    "lens_for",
    "LENSES",
    "LensView",
    "LevelFinding",
    "library_template",
    "Licensing",
    "load_aircraft",
    "load_airspace",
    "load_ats_structure",
    "load_facts",
    "load_hazards",
    "load_holding",
    "load_library",
    "load_navaids",
    "load_procedures",
    "load_profile",
    "load_register",
    "ManifestError",
    "max_holding_speed_kt",
    "mercator",
    "merge",
    "merge_libraries",
    "MinimaChange",
    "Minimum",
    "minimum_runway_width_m",
    "MissingCredential",
    "Navaid",
    "navaid_template",
    "NavaidKind",
    "NavaidRegister",
    "NavaidStatus",
    "NavaidUse",
    "ndjson",
    "Network",
    "network_for",
    "network_html",
    "network_svg",
    "NetworkDiagram",
    "NetworkEntry",
    "NetworkSweep",
    "Notam",
    "NotamKind",
    "NotamRegister",
    "notams_on_hazards",
    "notams_on_route",
    "Note",
    "Obstacle",
    "ObstacleChange",
    "ObstacleReview",
    "OLS_INSTRUMENT_DEPARTURE",
    "open_store",
    "OpenItem",
    "OperatorAssessment",
    "OperatorFleet",
    "OperatorProfile",
    "OperatorRecord",
    "OperatorSegment",
    "Origin",
    "Outage",
    "PANS_OPS_STRAIGHT",
    "parse_coordinate",
    "parse_position",
    "parse_route_string",
    "PavementCheck",
    "PavementRating",
    "PavementVerdict",
    "penetrates_ois",
    "Penetration",
    "plan_html",
    "plan_svg",
    "plan_view",
    "PlanView",
    "PlottedPoint",
    "Position",
    "Precedence",
    "Procedure",
    "procedure_template",
    "ProcedureKind",
    "ProcedureLeg",
    "ProcedureLink",
    "QLine",
    "QualityFinding",
    "QualityReport",
    "RatingSystem",
    "Redistribution",
    "reference_code",
    "register_template",
    "RegisteredNotam",
    "Registration",
    "Release",
    "render_board",
    "render_dossier",
    "required_gradient",
    "Requirement",
    "Resolution",
    "Restraint",
    "Retrospect",
    "retrospect",
    "review",
    "review_charts",
    "review_runway",
    "ReviewGate",
    "Revision",
    "rffs_category",
    "Role",
    "Route",
    "route_entities",
    "route_html",
    "route_profile",
    "route_svg",
    "RouteDiagram",
    "RouteDossier",
    "RouteExpansion",
    "RouteLeg",
    "RouteSegment",
    "RuntimeReport",
    "scope_of",
    "screen",
    "screen_clearances",
    "screen_climb",
    "screen_descent",
    "screen_hazards",
    "screen_holding",
    "screen_levels",
    "screen_navaids",
    "section",
    "Section",
    "SectionEntry",
    "SectionHolding",
    "Severity",
    "sha256_of",
    "SignificantPoint",
    "Source",
    "SourceFormat",
    "SourceKind",
    "SourceRef",
    "SourceRegistry",
    "SourceState",
    "SpeedBasis",
    "SqliteFactStore",
    "StaleAttestation",
    "standard_outbound_time_min",
    "StatusRow",
    "structure_template",
    "Subject",
    "SubjectKind",
    "Suitability",
    "Supervisor",
    "sweep",
    "to_json",
    "TrackOffset",
    "Transition",
    "Trigger",
    "Trip",
    "TripAssessment",
    "TurnDirection",
    "TypeCoverage",
    "TypeGap",
    "TypeReference",
    "TypeScreen",
    "Unexplained",
    "Usability",
    "usable",
    "validate",
    "view",
    "view_airspace",
    "worst_exposure",
]
