#!/usr/bin/env python3
"""Generate src/aeropub/notam_code.py — the ICAO Doc 8400 NOTAM Code.

The NOTAM Code is a fixed table. Decoding a Q-line by consulting a PDF at
runtime is neither fast nor auditable, so the table is vendored: five letters
in, plain language out, with no document to parse and no network call.

**This is a transcription, not the primary document.** It is assembled from
the `svoop/notam` Ruby library (MIT), whose author maintains the AIXM tooling
Ruby aviation projects use, and which encodes the Doc 8400 tables as data. That
provenance is recorded in the generated module so a reader knows what they are
trusting and can check it against the ICAO publication.

It was chosen over writing the table from memory for the obvious reason: this
is aviation safety data, a wrong mapping means a NOTAM filed under the wrong
subject, and a table nobody can trace to a source is one nobody can audit.

Re-run after checking upstream for changes:

    python3 tools/build_notam_code.py
"""

from __future__ import annotations

import datetime
import re
import sys
import urllib.request
from pathlib import Path

BASE = "https://raw.githubusercontent.com/svoop/notam/main"
TABLES_URL = f"{BASE}/lib/notam/translation.rb"
LOCALE_URL = f"{BASE}/lib/locales/en.yml"
OUT = Path(__file__).resolve().parent.parent / "src" / "aeropub" / "notam_code.py"

#: Ruby constant -> the name it gets in the generated module.
WANTED = {
    "SUBJECT_GROUPS": "SUBJECT_GROUPS",
    "SUBJECTS": "SUBJECTS",
    "CONDITION_GROUPS": "CONDITION_GROUPS",
    "CONDITIONS": "CONDITIONS",
    "TRAFFIC": "TRAFFIC",
    "PURPOSES": "PURPOSES",
    "SCOPES": "SCOPES",
    "CONTRACTIONS": "CONTRACTIONS",
}

#: Which locale section carries the English for each table.
LOCALE_SECTION = {
    "SUBJECT_GROUPS": "subject_groups",
    "SUBJECTS": "subjects",
    "CONDITION_GROUPS": "condition_groups",
    "CONDITIONS": "conditions",
    "TRAFFIC": "traffic",
    "PURPOSES": "purposes",
    "SCOPES": "scopes",
    "CONTRACTIONS": "contractions",
}


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def ruby_table(source: str, name: str) -> dict[str, str]:
    """Code -> symbol, from a Ruby constant hash."""
    match = re.search(rf"^\s*{name}\s*=\s*\{{(.*?)^\s*\}}", source, re.M | re.S)
    if match is None:
        raise SystemExit(f"{name} not found upstream — the layout changed")
    return dict(re.findall(r"'([A-Z0-9/ -]{1,16})'\s*=>\s*:([\w?]+)", match.group(1)))


def locale_table(source: str, section: str) -> dict[str, str]:
    """Symbol -> English, from the i18n YAML."""
    match = re.search(
        rf"^  {section}:\s*$(.*?)(?=^  \w+:\s*$|\Z)", source, re.M | re.S
    )
    if match is None:
        raise SystemExit(f"locale section {section} not found — the layout changed")
    found = {}
    for line in match.group(1).splitlines():
        entry = re.match(r'^\s{4}([\w?]+):\s*"?(.*?)"?\s*$', line)
        if entry:
            found[entry.group(1)] = entry.group(2)
    return found


def main() -> int:
    print(f"fetching {TABLES_URL}")
    tables = fetch(TABLES_URL)
    print(f"fetching {LOCALE_URL}")
    locale = fetch(LOCALE_URL)

    built: dict[str, dict[str, str]] = {}
    unresolved: list[str] = []
    for ruby_name, out_name in WANTED.items():
        codes = ruby_table(tables, ruby_name)
        english = locale_table(locale, LOCALE_SECTION[ruby_name])
        joined = {}
        for code, symbol in sorted(codes.items()):
            text = english.get(symbol)
            if text is None:
                # A symbol with no English is carried as the symbol, spelled
                # out. Dropping it would silently shrink the table.
                text = symbol.replace("_", " ")
                unresolved.append(f"{out_name}[{code}] = :{symbol}")
            joined[code] = text
        built[out_name] = joined
        print(f"  {out_name:18} {len(joined):4} entries")

    if unresolved:
        print(f"\n{len(unresolved)} codes had no English text; carried as their symbol:")
        for line in unresolved[:10]:
            print("   ", line)

    today = datetime.date.today().isoformat()
    body = [
        '"""ICAO Doc 8400 NOTAM Code — the whole table, as data.',
        "",
        "Generated by ``tools/build_notam_code.py``. Do not edit by hand; edit the",
        "generator and re-run it, so the table stays traceable to its source.",
        "",
        "Five letters in, plain language out. A Q-code is a fixed table, and",
        "consulting a PDF at runtime to decode one is neither fast nor auditable.",
        "",
        "**A transcription, not the primary document.** Assembled from the",
        "``svoop/notam`` Ruby library (MIT), which encodes the Doc 8400 tables as",
        "data. Written from a source rather than from memory because this is",
        "aviation safety data: a wrong mapping files a NOTAM under the wrong",
        "subject, and a table nobody can trace is one nobody can audit. Check it",
        "against the ICAO publication before relying on it for anything that",
        "matters, and re-run the generator when Doc 8400 is amended.",
        "",
        "A code absent from these tables is absent. Nothing here guesses, and the",
        "reader that uses them reports an unmapped code as unmapped.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "#: Where this table came from, so a value can be traced out of the code.",
        "NOTAM_CODE_SOURCE: dict[str, str] = {",
        '    "document": "ICAO Doc 8400 — Procedures for Air Navigation Services: '
        'ICAO Abbreviations and Codes (PANS-ABC), Part 2, The NOTAM Code",',
        '    "transcribed_from": "https://github.com/svoop/notam",',
        '    "transcription_licence": "MIT",',
        f'    "retrieved_on": "{today}",',
        '    "generator": "tools/build_notam_code.py",',
        "}",
        "",
    ]

    docs = {
        "SUBJECT_GROUPS": "First letter of the subject — the broad category.",
        "SUBJECTS": "Letters two and three of a Q-code: what the NOTAM is about.",
        "CONDITION_GROUPS": "First letter of the condition.",
        "CONDITIONS": "Letters four and five: what has happened to the subject.",
        "TRAFFIC": "Q-line traffic field: which rules the NOTAM concerns.",
        "PURPOSES": "Q-line purpose field: why it was issued.",
        "SCOPES": "Q-line scope field: what it applies to.",
        "CONTRACTIONS": "ICAO abbreviations used in NOTAM text (Doc 8400 Part 1).",
    }
    for name, table in built.items():
        body.append(f"#: {docs[name]}")
        body.append(f"{name}: dict[str, str] = {{")
        for code, text in table.items():
            escaped = text.replace('\\', '\\\\').replace('"', '\\"')
            body.append(f'    "{code}": "{escaped}",')
        body.append("}")
        body.append("")

    OUT.write_text("\n".join(body), encoding="utf-8")
    print(f"\nwrote {OUT} ({OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
